---
version: "3.3"

services:
  printer:
    build: .
    container_name: printer
    env_file: .env
    ports:
      - "8000:8000"
    networks:
      - printer
    volumes:
      - ./volume:/home/superquinquin/printer/volume

networks:
  printer:
